### PR TITLE
Add Multirun stop button

### PR DESCRIPTION
**Pull request by handras**
+ Added a stop button to toolbar to close the opened windows
+ Added tooltips for the buttons
* renamed variable to meaningful names
* error checking when starting additional windows

### CODE REVIEW

**Comment by handras** [comment]
Hello @cyraid,
I believe this is the latest repo uploaded to the asset library, but are you the developer?

**Comment by cyraid** [comment]
@handras I am a collaborator yup! I somehow don't get notifications for this repo, I'm not sure why! But I checked the commit, looks good! One small thing, could you bump the version from 2.0.3 to 2.0.4 and go ahead and add your name to the author in `plugin.cfg` (if you want)?

**Review by cyraid — APPROVED** [review]
Looks good! Thank you for the changes. :)

**Comment by cyraid** [comment]
@xiezi5160 would you be able to push the update on godot asset website?

**Comment by xiezi5160** [comment]
> @xiezi5160 would you be able to push the update on godot asset website?

@cyraid Okay, I'll bring it up now, thank you ~

**Comment by xiezi5160** [comment]
@cyraid I have completed the submission, thank you for your hard maintenance ~
image

**Comment by cyraid** [comment]
@xiezi5160 you're welcome! I'd push it on the asset library too but the last time I checked they don't allow multiple collaborators.

**Comment by xiezi5160** [comment]
> @xiezi5160 you're welcome! I'd push it on the asset library too but the last time I checked they don't allow multiple collaborators.
@cyraid Yes, the Godot Asset Library does not allow multiple people to collaborate.
It's okay, if you need it in the future, you can @ me, or you can resubmit a plugin in Godot Asset Library.

**Comment by cyraid** [comment]
@xiezi5160 it's okay. I'd rather keep this repository if you're willing, because there's already another multirun repo, if there were 3 it'd start to seem confusing haha .. I'll ping you when we need to push if you're okay with it. ^_^

**Comment by xiezi5160** [comment]
> @xiezi5160 it's okay. I'd rather keep this repository if you're willing, because there's already another multirun repo, if there were 3 it'd start to seem confusing haha .. I'll ping you when we need to push if you're okay with it. ^_^

@cyraid Okay, as you wish, haha!

**Pull request merged**
